<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="bin\Debug\net8.0-windows\CHICKEN_FINGERS_APP.deps.json" />
		<Content Include="bin\Debug\net8.0-windows\CHICKEN_FINGERS_APP.runtimeconfig.json" />
		<Content Include="obj\CHICKEN_FINGERS_APP.csproj.nuget.dgspec.json" />
		<Content Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.csproj.FileListAbsolute.txt" />
		<Content Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.designer.deps.json" />
		<Content Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.designer.runtimeconfig.json" />
		<Content Include="obj\project.assets.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="bin\Debug\net8.0-windows\CHICKEN_FINGERS_APP.dll" />
		<None Include="bin\Debug\net8.0-windows\CHICKEN_FINGERS_APP.exe" />
		<None Include="bin\Debug\net8.0-windows\CHICKEN_FINGERS_APP.pdb" />
		<None Include="bin\Debug\net8.0-windows\FontAwesome.Sharp.dll" />
		<None Include="bin\Debug\net8.0-windows\Krypton.Toolkit.dll" />
		<None Include="obj\CHICKEN_FINGERS_APP.csproj.nuget.g.props" />
		<None Include="obj\CHICKEN_FINGERS_APP.csproj.nuget.g.targets" />
		<None Include="obj\Debug\net8.0-windows\apphost.exe" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_.5FDF8C48.Up2Date" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.AssemblyInfoInputs.cache" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.assets.cache" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.csproj.AssemblyReference.cache" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.csproj.BuildWithSkipAnalyzers" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.csproj.CoreCompileInputs.cache" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.csproj.GenerateResource.cache" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.dll" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.GeneratedMSBuildEditorConfig.editorconfig" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.genruntimeconfig.cache" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.pdb" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.Properties.Resources.resources" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.Visuals.Login.resources" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.Visuals.MainForm.resources" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.Visuals.SecondaryForm.resources" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.Visuals.UC_btnGuardarCompra.resources" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.Visuals.UC_Historial.resources" />
		<None Include="obj\Debug\net8.0-windows\CHICKEN_FINGERS_APP.Visuals.UC_Ventas.resources" />
		<None Include="obj\Debug\net8.0-windows\refint\CHICKEN_FINGERS_APP.dll" />
		<None Include="obj\Debug\net8.0-windows\ref\CHICKEN_FINGERS_APP.dll" />
		<None Include="obj\Debug\net8.0-windows\TempPE\Properties.Resources.Designer.cs.dll" />
		<None Include="obj\project.nuget.cache" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
		<PackageReference Include="Krypton.Toolkit" Version="95.25.10.293" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Properties\Resources.resx">
			<Generator>ResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>
